#!/bin/sh

NTP_SERVER=ntp.ubuntu.com
INITIAL_DATE=2014-08-04

if ! /usr/bin/network-monitor check; then
    /usr/bin/network-monitor hotspot
    sudo date --set ${INITIAL_DATE}
else
	ntpdate ${NTP_SERVER}
fi