#!/bin/sh

INITIAL_DATE=2014-08-04

if ! ntp-wait -n 3 -n 3; then
	sudo date --set ${INITIAL_DATE}
	if ! /usr/bin/network-monitor check; then
    		/usr/bin/network-monitor hotspot
	fi
fi

start astrobox