#!/bin/sh

stop_wifi_ap() {
    ### stop services dhcpd and hostapd
    service isc-dhcp-server stop
    service hostapd stop

    ### Removing hostapd config file
    rm /etc/hostapd/hostapd.conf

    ### disable IP forwarding
    #echo 0 > /proc/sys/net/ipv4/ip_forward
    #iptables -t nat -D POSTROUTING -s 10.10.0.0/16 -o $ext_interface -j MASQUERADE 2>/dev/null

    ip link set dev wlan1 down
    ip address del 10.10.0.1/24 dev wlan1
}

start_wifi_ap() {
    ### give a static IP to the wifi interface
    ip link set dev wlan1 up
    ip address add 10.10.0.1/24 dev wlan1

    ### enable IP forwarding
    #echo 1 > /proc/sys/net/ipv4/ip_forward
    #iptables -t nat -A POSTROUTING -s 10.10.0.0/16 -o $ext_interface -j MASQUERADE

    ##Creating hostapd conf file
    local HOSTNAME=`hostname`
    contents=$(sed -e "s|\${NETWORK_NAME}|${HOSTNAME}|g" < /etc/hostapd/hostapd.conf.template)
    echo "$contents" > /etc/hostapd/hostapd.conf

    ### start services dhcpd and hostapd
    service hostapd start
    service isc-dhcp-server start
}

### start/stop wifi access point
case "$1" in
    start) start_wifi_ap ;;
    stop)  stop_wifi_ap  ;;
esac