#!/bin/sh

PACKAGES="python-pip python-dev haproxy isc-dhcp-server hostapd nscd network-manager"

for pkg in $PACKAGES; do
	if dpkg --get-selections | grep -q "^$pkg[[:space:]]*install$" >/dev/null; then
        	echo "$pkg is already installed"
	else
		if apt-get -qq install $pkg; then
			echo "Successfully installed $pkg"
		else
			echo "Failed to install $pkg"
			exit 1
		fi
	fi
done

cp conf/haproxy.cfg /etc/haproxy/haproxy.cfg
cp conf/haproxy.default /etc/default/haproxy

update-rc.d isc-dhcp-server disable
update-rc.d hostapd disable

cp /etc/default/isc-dhcp-server /etc/default/isc-dhcp-server.bak
sed -i /etc/default/isc-dhcp-server \
	-e "/INTERFACES=/c INTERFACES=wlan1"

cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcp.conf.bak
sed -i /etc/dhcp/dhcpd.conf \
    	-e 's/^option domain-name/#option domain-name/' \
    	-e 's/^option domain-name-servers/#option domain-name-servers/' \
    	-e 's/^default-lease-time/#default-lease-time/' \
    	-e 's/^max-lease-time/#max-lease-time/'

sed -i /etc/dhcp/dhcpd.conf \
    	-e '/subnet 10.10.0.0 netmask 255.255.255.0/,+4 d'

cat <<EOF >> /etc/dhcp/dhcpd.conf
	subnet 10.10.0.0 netmask 255.255.255.0 {
        	range 10.10.0.2 10.10.0.16;
        	option domain-name-servers 8.8.4.4, 208.67.222.222;
        	option routers 10.10.0.1;
	}
EOF

cp conf/hostapd.conf /etc/hostapd/hostapd.conf

cp /etc/default/hostapd /etc/default/hostapd.bak
sed -i /etc/default/hostapd \
	-e '/DAEMON_CONF=/c DAEMON_CONF="/etc/hostapd/hostapd.conf"'

if [ ! -f /etc/init.d/wifi_access_point ]; then
	cp scripts/wifi_access_point /etc/init.d/wifi_access_point
	chmod +x /etc/init.d/wifi_access_point
fi

if [ ! -f /usr/bin/network-monitor ]; then
	cp scripts/network-monitor /usr/bin/network-monitor
	chmod +x /usr/bin/network-monitor
fi

pip install -r ../requirements.txt

if [ ! -f /usr/bin/astrobox ]; then
	cp init/astrobox.default /etc/default/astrobox
	cp init/astrobox.init /etc/init.d/astrobox
	chmod +x /etc/init.d/astrobox

	cp init/astrobox /usr/bin/astrobox
	chmod +x /usr/bin/astrobox

	update-rc.d astrobox defaults
fi

if ! grep -q "### AstroBox rc.local ###" /etc/rc.local; then
	cat init/rc.local >> /etc/rc.local 
fi

if [ ! -f /home/ubuntu/AstroBox/local/users.yaml ]; then
	cp conf/octoprint/users.yaml /home/ubuntu/AstroBox/local/users.yaml
fi

if [ ! -f /home/ubuntu/AstroBox/local/config.yaml ]; then
	cp conf/octoprint/config.yaml /home/ubuntu/AstroBox/local/config.yaml
fi
